---
title: "Untitled"
output: html_document
---

```{r}
rm(list=ls())
library(readr)
library(dplyr)
getwd()
data <- read_csv("Dataset_Modelos.csv")
colnames(data)
```
```{r}


tbl <- table(data$suffix,data$phishing)
tablatbl
```

```{r}
data$acerto=ifelse(data$phishing==data$Prediccion,1,0)
data <- subset(data, select=c((ncol(data)-3):ncol(data),1:(ncol(data)-4)))
data <- data %>%
  mutate(sisi=ifelse(phishing==1 & Prediccion==1,1,0),
  nono=ifelse(phishing==0 & Prediccion==0,1,0))
```

```{r}
aux<-subset(data,select=c(1:4,6,198:236))
View(aux)
```

```{r}
table(data$path_n_guion)



table(data$phishing,data$sisi,data$phishing)
ail(table(aux$metric_google,aux$acerto),20)
data$domain_bit=ifelse(data$domain=="bit",1,0)
print("tabla, domain bit, phishing")
table(data$domain_bit,data$phishing)
print("tabla url length, phishing")
table(data$metric_d_amazon,data$acerto)

table(data$metric_s_google,data$acerto)
print("tabla scheme, es fishing y predice bien")
a=table(data$scheme,data$acerto)
a
a[1,2]/(a[1,2]+a[1,1])
a[2,2]/(a[2,2]+a[2,1])
table(data$dom_ip,data$acerto)
```
```{r}
data %>% select(suffix2, phishing, Prediccion )%>%  
  group_by(suffix2,phishing,Prediccion) %>% 
    summarise(n())
```

