---
title: "NB - Analisis Resultados"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
```


```{r}
results <- read_csv("Proyecto A/03 - Comparacion Modelos/Resultados.csv")
```

```{r, fig.height= 4.5, fig.width= 12}
results %>%
  filter(Metric %in% c("Accuracy", "Sensitivity", "Specificity")) %>%
  ggplot(aes(x = reorder(as.factor(Models), -Value), y = Value, color = Data, group = Data)) +
  geom_point(size = 3) +
  geom_line() +
  expand_limits(y = c(0.80,1)) +
  labs(title = "Comparación Modelos",
       y = "Valor",
       x = "Modelos") +
  facet_wrap(.~Metric) +
  theme_bw()
```


```{r, fig.height= 8, fig.width= 12}
results %>%
  #filter(Metric %in% c("Accuracy", "Sensitivity", "Specificity")) %>%
  ggplot(aes(x = reorder(as.factor(Models), -Value), y = Value, color = Data, group = Data)) +
  geom_point(size = 3) +
  geom_line() +
  expand_limits(y = c(0.80,1)) +
  labs(title = metric,
       y = metric,
       x = "Modelos") +
  facet_wrap(.~Metric) +
  theme_bw()
```


```{r, fig.width=8, fig.height=6}
metrics <- c("Accuracy", "Sensitivity", "Specificity", "Precision", "Recall")
for (metric in metrics){
  print(results %>%
  filter(Metric == metric) %>%
  ggplot(aes(x = reorder(as.factor(Models), -Value), y = Value, color = Data, group = Data)) +
  geom_point(size = 3) +
  geom_line() +
  expand_limits(y = c(0.80,1)) +
  labs(title = metric,
       y = metric,
       x = "Modelos") +
  theme_bw())
}
```


```{r}
results %>%
  filter(Data == "Test",
         Metric %in% c("Accuracy", "Sensitivity", "Specificity")) %>%
  ggplot()+
  geom_col(aes(x = Metric, y = Value, fill = reorder(as.factor(Models), -Value)), position = "dodge", color = "black")+
  expand_limits(y = c(0,1)) +
  scale_fill_brewer(direction = -1, type = "div")+
  labs(title = "Comparación Columnas",
       fill = "Modelos") +
  #coord_flip() +
  theme_bw()
```























