


# Paquetes

```{r Paquetes}
library(dplyr)
library(ggplot2)
library(corrplot)
library(fastDummies)
library(purrr)
library(tidyr)
library(readr)
library(caret)
```

```{r}
# Linux
getwd()
data <- read_csv('Proyecto A/00 - Creación Dataset y Variables/Dataset_Modelos.csv')
```


```{r}
# Windows
data <- read_csv('../00 - Creación Dataset y Variables/Dataset_Modelos.csv')

```

Armo un vector con las variables no numericas que no van en el analisis. Luego armo el dataset data_numeric eliminando dichas variables del dataset.

```{r}
char_vars <- c("X1", 
               "url", 
               "scheme", 
               "domain_complete", 
               "domain", 
               "subdomain", 
               "suffix", 
               "domain_subdomain", 
               "path", 
               "suffix2")

df <- data %>%
  select(-char_vars)
```
Divido el dataset en X,Y, train y test. 

```{r}
set.seed(45)
rows <- sample(nrow(df))
df <- df[rows,]
train_index <- createDataPartition(y = df$phishing, times = 1, p = 0.8, list = FALSE)
train <- df[train_index,]
test <- df[-train_index,]
```




Regresión logistica: 

```{r}
default_glm_mod = train(
  factor(phishing)~.,
  train,
  trControl = trainControl(method = "cv", number = 5),
  method = "glm",
  family = "binomial",
  na.action=na.exclude
)
```

```{r}
default_glm_mod
default_glm_mod$results
x_test <- test[,2:224]
y_test <- test[,1]
predictions <- predict(default_glm_mod, x_test)
confusionMatrix(predictions, factor(y_test))
                
```

